### ISSUE TITLE
Include IntelliJ (and/or Gradle) project files

### ISSUE THREAD

**Issue by transalexys** [Exenco/Light-Show#3]
Would you be able to include either a Gradle project or the IntelliJ project files? This would make it easier for others to set up and build the project locally to contribute changes. A gradle project would be preferred, too, to allow doing CI builds and using IDEs other than Gradle - there's documentation [here](https://www.jetbrains.com/help/idea/gradle.html#convert_project_to_gradle) to create a IntelliJ project to a Gradle project.

**Comment by Exenco** [comment]
I have been thinking about this but there is no good way. In order to access packets in the latest Spigot version you need to include the obfuscated jar-files you get when setting up a server. That in mind any proper project setup - no matter whether Gradle, Maven, etc - sadly isn't possible.

**Comment by transalexys** [comment]
I looked at this a bit after creating the issue, have you considered
replacing the references to the obfuscated jars with references to
something like BKCommonLib to handle the version-specific classes in a
version independent way?

**Comment by Exenco** [comment]
Yes, I tried using ProtocolLib but frankly I didn't like it that much. Never heard of BKCommonLib before but why not give it a shot.

**Comment by Exenco** [comment]
It has been some time and now its finally here. Sadly no ProtocolLib or BkCommonLib, trying to implement either just requires too much refactoring for me willing to do.
